name: Build, Test, and Upload Image

on:
  push:
    branches: [ develop ]

env:
  PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  IMAGE: ${{ github.event.repository.name }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:

  build-publish:
    name: Build, Test, and Push Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Set up gcloud"
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        
    - name: Authenticate with gcloud
      run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    - name: Build Image
      run: |-
        docker build --build-arg GH_TOKEN=$GH_TOKEN -t "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" -t "gcr.io/$PROJECT_ID/$IMAGE:latest" .

    # Push the Docker image to Google Container Registry
    - name: Push Image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE"